from pathlib import Path
p=Path('/home/ubuntu/jarvis-operator/client/src/pages/Home.tsx')
s=p.read_text()
old='const found = await new Promise<google.maps.places.PlaceResult[]>((resolve, reject) => service.textSearch({ query: `${query} near ${area}, Hyderabad, Telangana, India`, location: center, radius: Number(radius) }, (items, status) => status === google.maps.places.PlacesServiceStatus.OK ? resolve(items ?? []) : reject(new Error(status === google.maps.places.PlacesServiceStatus.ZERO_RESULTS ? "No businesses found in this area." : "Places search failed.")))); found.slice(0, 20).forEach((place) => { if (place.geometry?.location) markers.push(new google.maps.Marker({ map, position: place.geometry.location, title: place.name })); }); const mapped = await Promise.all(found.slice(0, 20).map(async (place, index) => {'
new='const found: google.maps.places.PlaceResult[] = []; let page = 0; let nextPage: google.maps.places.PlaceSearchPagination | undefined; do { const batch = await new Promise<{ items: google.maps.places.PlaceResult[]; pagination?: google.maps.places.PlaceSearchPagination }>((resolve, reject) => service.textSearch({ query: `${query} near ${area}, Hyderabad, Telangana, India`, location: center, radius: Number(radius) }, (items, status, pagination) => status === google.maps.places.PlacesServiceStatus.OK ? resolve({ items: items ?? [], pagination }) : status === google.maps.places.PlacesServiceStatus.ZERO_RESULTS ? resolve({ items: [], pagination }) : reject(new Error("Places search failed.")))); found.push(...batch.items); nextPage = batch.pagination; page += 1; if (nextPage?.hasNextPage && page < 3) await new Promise((resolve) => window.setTimeout(resolve, 2200)); else break; } while (nextPage?.hasNextPage); const mapped = await Promise.all(found.map(async (place, index) => {'
if old not in s: raise SystemExit('search block not found')
s=s.replace(old,new)
old2='const details = place.place_id ? await new Promise<google.maps.places.PlaceResult>((resolve) => service.getDetails({ placeId: place.place_id as string, fields: ["name", "formatted_address", "website", "formatted_phone_number", "international_phone_number", "rating", "user_ratings_total"] }, (detail) => resolve(detail ?? place))) : place; const probability = probabilityFor(details.rating, details.user_ratings_total, details.website); return { id: details.place_id ?? `place-${index}`, business: details.name ?? "Unnamed business", niche: query, location: details.formatted_address ?? area, score: scoreFor(probability, details.website, details.international_phone_number ?? details.formatted_phone_number), probability, contact: "Not enriched", phone: details.international_phone_number ?? details.formatted_phone_number, lastTouch: "Found just now", value: 0, initials: (details.name ?? "B").split(" ").slice(0, 2).map((word) => word[0]).join("").toUpperCase(), address: details.formatted_address, website: details.website, placeId: details.place_id, stage: "New" as Stage, followUpDate: todayISO(), replyStatus: "none" as const, source: "Google Places" }; })); setResults(mapped);'
new2='const details = place.place_id ? await new Promise<google.maps.places.PlaceResult>((resolve) => service.getDetails({ placeId: place.place_id as string, fields: ["name", "formatted_address", "website", "formatted_phone_number", "international_phone_number", "rating", "user_ratings_total"] }, (detail) => resolve(detail ?? place))) : place; if (details.website) return null; const probability = probabilityFor(details.rating, details.user_ratings_total); return { id: details.place_id ?? `place-${index}`, business: details.name ?? "Unnamed business", niche: query, location: details.formatted_address ?? area, score: scoreFor(probability, undefined, details.international_phone_number ?? details.formatted_phone_number), probability, contact: "Not enriched", phone: details.international_phone_number ?? details.formatted_phone_number, lastTouch: "Found just now", value: 0, initials: (details.name ?? "B").split(" ").slice(0, 2).map((word) => word[0]).join("").toUpperCase(), address: details.formatted_address, placeId: details.place_id, stage: "New" as Stage, followUpDate: todayISO(), replyStatus: "none" as const, source: "Google Places" } as Lead; })).then((items) => items.filter((item): item is Lead => Boolean(item))); mapped.forEach((lead) => { const place = found.find((item) => item.place_id === lead.placeId); if (place?.geometry?.location) markers.push(new google.maps.Marker({ map, position: place.geometry.location, title: lead.business })); }); setResults(mapped);'
if old2 not in s: raise SystemExit('mapping block not found')
s=s.replace(old2,new2)
s=s.replace('const addLead = (lead: Lead) => { if (duplicateOf(lead))', 'const addLead = (lead: Lead) => { if (lead.website) { toast("Businesses with websites are excluded from lead discovery"); return; } if (duplicateOf(lead))')
s=s.replace('const addAll = () => { const fresh = results.filter((lead) => !duplicateOf(lead));', 'const addAll = () => { const fresh = results.filter((lead) => !lead.website && !duplicateOf(lead));')
s=s.replace('setResults(mapped); if (!mapped.length) setError("No businesses found in this area.");', 'setResults(mapped); if (!mapped.length) setError("No businesses without an existing website were found in this area.");')
p.write_text(s)
Path('/home/ubuntu/jarvis-operator/.tmp_lead_discovery.py').unlink()
